#  Configure Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/central_db
    username: root
    password: null
    driver-class-name: com.mysql.jdbc.Driver
    
#  Configure JPA
  jpa:                    
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
  